# Generated by Django 5.1 on 2024-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default='BQC1rdIURzug889YfwpDK-MpN2z2pbVlQh0qz5U9ijb_tR3303sp43w3PNDyqQU0etml4FQxZo_-VPHb7H1fjb6mntOA2uwnDk9iow6_0vm9vwH0xnkYXZn7Q3e5Dqd0oPIgw1ntCHh9LdyDT112qF5BCsC5u5ug403UV_k38QpRcpgCEXiJJYdv3WJU0Fe9mInfbYe7w-qoihlffKY', max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(default='AQA45DF00fx0ac6dz_IvTQtBH7Ey00erTp9GBL-v-bZY17Hv51sFPmIK4ynYbU1vmxvIkwNXdn2-s-l_HojHaG5yhR7H84aCFiuf9yO2ln59zXaCihb6Vg2QxbmXALfnLzU', max_length=255),
        ),
    ]
