# Generated by Django 5.1 on 2024-09-09 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0002_remove_spotifytoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 9, 22, 30, 272812, tzinfo=datetime.timezone.utc)),
        ),
    ]
