# Generated by Django 5.1 on 2024-09-10 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0003_alter_spotifytoken_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 10, 7, 46, 45, 209667, tzinfo=datetime.timezone.utc)),
        ),
    ]
