# Generated by Django 5.1 on 2024-09-10 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0004_alter_spotifytoken_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 10, 8, 17, 236536, tzinfo=datetime.timezone.utc)),
        ),
    ]
