# Generated by Django 5.1 on 2024-09-10 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0006_alter_spotifytoken_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 12, 43, 27, 856461, tzinfo=datetime.timezone.utc)),
        ),
    ]
