# Generated by Django 5.1 on 2024-09-10 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0008_alter_spotifytoken_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 13, 22, 21, 895212, tzinfo=datetime.timezone.utc)),
        ),
    ]
