# Generated by Django 5.1 on 2024-09-21 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0016_alter_spotifytoken_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 8, 45, 20, 994798, tzinfo=datetime.timezone.utc)),
        ),
    ]
